### ISSUE TITLE
Question: Why choosing such a complex .js structure

### ISSUE THREAD

**Issue by CesMak** [miguelgrinberg/microflack_ui#6]
Hey Miguel,

for me your ui service has a very complex structure (lot of js files in views and models) and is far away from my monolithic application. 

My monolithic app consists of:
templates\layout1.html
templates\layout2.html
templates\login.html 
etc.
That is fine and pretty much the same as your index.html

But for the views I use a forms.py file and FlaskForms like this:
```
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import  SelectField, StringField, IntegerField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError

class LoginForm(FlaskForm):
    email    = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Passwort', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    terms    = BooleanField('Ich habe, die Nutzungsbedingungen gelesen und aktzeptiere alle Cookies.', validators=[DataRequired()])
    submit   = SubmitField('Login')
```
Does it has a particular reason why you choose to use your views in .js files?

Also for my website I use many different routes. For your minimal example multiple routes make probably no sense.

**Comment by miguelgrinberg** [comment]
> Does it has a particular reason why you choose to use your views in .js files?

I built this example as a single-page app (SPA). I thought that worked best for this project. If you want to build a traditional server-rendered UI that's fine too, though that is going to make splitting your app into microservices more challenging.

> Also for my website I use many different routes.

An SPA can also use many routes, but they are all handled within JavaScript, with a single server-side route for the whole application.

**Comment by CesMak** [comment]
So just to not misunderstand you, If I want to use FlaskForms instead of defining the forms in a .js file, I will have more challenges splitting up my app into microservices?

I guess you chose Client Side Rendering instead of Server Side Rendering cause an app like microflack is highly dynamic and in such a case client side rendering should be preferred.

**Comment by miguelgrinberg** [comment]
Yes. In general microservices are coded as APIs, so then you have an SPA making calls to the services from JavaScript.

I'm not sure how a microservices app would look when based on server-side rendering. I have never seen an example of that done.
